### test auth
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username": "Dennis",
    "email": "dennis@gmail.com",
    "password": "12345688"
}

### test auth
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username": "Test",
    "email": "test@gmail.com",
    "password": "12345688"
}